version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: besoindunjob.fr
    ports:
      - '3306:3306'
